sudo:required
services: 
    - docker

before_install: 
    - docker build -t akashmaggon/complex-container -f ./client/Dockerfile.dev ./client
    
script: 
    - docker run -e CI=true akashmaggon/complex-container npm test -- --coverage
    

after_success:
    - docker build -t akashmaggon/complex-container-client ./client
    - docker build -t akashmaggon/complex-container-nginx ./nginx
    - docker build -t akashmaggon/complex-container-worker ./worker
    - docker build -t akashmaggon/complex-container-server ./server   
    - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_ID" --password-stdin
    - docker push akashmaggon/complex-container-client
    - docker push akashmaggon/complex-container-server
    - docker push akashmaggon/complex-container-nginx
    - docker push akashmaggon/complex-container-worker    

